# Universal Windows Platform

# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted Windows 2019 with VS2019
  demands: msbuild


variables:
  solution: '**/*.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Debug'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'

steps:

- task: DotNetCoreCLI@2  
  inputs:
    command: custom
    custom: tool
    arguments: install -g nbgv
  displayName: Install NBGV tool

- script: nbgv cloud -c
  displayName: Set Version

- task: VSBuild@1
  inputs:
    platform: 'x86'
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxPackageDir="$(appxPackageDir)" /p:AppxBundle=Never /p:UapAppxPackageBuildMode=StoreUpload'
