# Universal Windows Platform

# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted Windows 2019 with VS2019
  demands: msbuild


variables:
  solution: '**/*.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Debug'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'

steps:
- task: NuGetToolInstaller@0

# - task: '333b11bd-d341-40d9-afcf-b32d5ce6f23b@2'
#   inputs:
#     restoreSolution: '$(solution)'

# - task: '333b11bd-d341-40d9-afcf-b32d5ce6f23b@2'
#   displayName: 'NuGet restore'
#   inputs:
#     restoreSolution: '**/*.sln'
#     feedsToUse: config
#     nugetConfigPath: '**/.nuget/NuGet.config'

- task: '333b11bd-d341-40d9-afcf-b32d5ce6f23b@2'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: VSBuild@1
  inputs:
    platform: 'x86'
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxPackageDir="$(appxPackageDir)" /p:AppxBundle=Never'
